spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      show-sql: true
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/json
    driverClassName: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: quanglinh821997@gmail.com
    password: ynhgyescitlgehsy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#      springframework: DEBUG

